version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: homelab-backstage-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123!
      POSTGRES_DB: homelab-backstage-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  catalog:
    build:
      context: ./catalog
      dockerfile: Dockerfile
    container_name: homelab-catalog
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./catalog:/docs
  
  # This is just an example to get a shared volume for backstage to be able to acecss the catalog files.
  # Maybe add a external storage container solution later?
  backstage:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ./catalog:/catalog


volumes:
  postgres_data:

